---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-mariadb
spec:
  accessModes:
    - {{ .Values.pvcAccessModes }}
  resources:
    requests:
      storage: {{ .Values.pvcStorageCapacity }}
---
