---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmapName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-mariadb
data:
  my.cnf: |
    [mysqld]
    lower_case_table_names=1
    max_allowed_packet=32M
    character-set-server=utf8
    collation-server=utf8_unicode_ci
    symbolic-links = 0
    skip_name_resolve
    ignore-db-dir=lost+found
    ignore-db-dir=.trashcan
    datadir=/var/lib/mysql/data
---
