apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-mariadb
spec:
  ports:
  - name: {{ .Values.portName }}
    port: {{ .Values.port }}
  selector:
    app: vprotect-mariadb
  clusterIP: None
