apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: vprotect-mariadb
spec:
  ports:
  - name: mysql
    port: {{ .Values.port }}
  selector:
    app: vprotect-mariadb
  clusterIP: None
