---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.node.svcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-node
spec:
  ports:
  - name: {{ .Values.node.svcName }}
    port: {{ .Values.node.containerPort }}
  selector:
    app: vprotect-node
---
