---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.node.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-node
spec:
  storageClassName: {{ .Values.node.storageClassName }}
  accessModes: 
  - {{ .Values.node.pvcAccessModes }}
  resources:
    requests:
      storage: {{ .Values.node.pvcStorageCapacity }}
---
