kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vprotect-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: vprotect-operator
  namespace: vprotect-storware
roleRef:
  kind: ClusterRole
  name: vprotect-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
