apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vprotect-operator-clusterrole
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
