---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprotect-mariadb
  labels:
    app: vprotect-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprotect-mariadb
  template:
    metadata:
      labels:
        app: vprotect-mariadb
    spec:
      containers:
      - name: mariadb
        image: registry.redhat.io/rhel8/mariadb-103
        env:
        - name: MYSQL_USER
          value: vprotect
        - name: MYSQL_PASSWORD
          value: vprotect
        - name: MYSQL_DATABASE
          value: vprotect
        - name: MYSQL_DEFAULTS_FILE
          value: /var/lib/mysql/data/conf/my_custom.cnf
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql/data
        - name: mariadb-config
          mountPath: /var/lib/mysql/data/conf
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - "-c"
            - exec mysqladmin status -uroot
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - "-c"
            - exec mysqladmin status -uroot
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: mariadb-config
        configMap:
          name: mariadb-config
          items:
          - key: my.cnf
            path: my_custom.cnf
---
