---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: vprotect-mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    app: vprotect-mariadb
  clusterIP: None
---