{{- if .Values.server.routes.insecureRoute.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.server.routes.insecureRoute.name }}
  labels:
    app: vprotect-server
spec:
  to:
    kind: Service
    name: {{ .Values.server.serviceName }}
    weight: 100
  port:
    targetPort: vprotect-server-http
  wildcardPolicy: None
{{- end }}
