{{- if .Values.server.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-vprotect
  labels:
    app: vprotect-server
spec:
  rules:
    - host: "ingress-vprotect-{{ .Release.Namespace }}.{{ .Values.server.ingress.subDomain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.server.serviceName }}
              servicePort: 8080
{{- end }}
