---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprotect-pv-claim
  labels:
    app: vprotect-node
spec:
  storageClassName: ibmc-block-bronze
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
