apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vprotectnodes.vprotect.example.com
spec:
  group: vprotect.example.com
  names:
    kind: VprotectNode
    listKind: VprotectNodeList
    plural: vprotectnodes
    singular: vprotectnode
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
