apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vprotectdbservers.vprotect.example.com
spec:
  group: vprotect.example.com
  names:
    kind: VprotectDBServer
    listKind: VprotectDBServerList
    plural: vprotectdbservers
    singular: vprotectdbserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
