apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vprotect-helm-operator-scc-admin
  namespace: demo-rhel
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
