kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vprotect-scc-admin
subjects:
- kind: ServiceAccount
  name: vprotect-helm-operator
  namespace: demo-rhel
roleRef:
  kind: ClusterRole
  name: vprotect-helm-operator-scc-admin
  apiGroup: rbac.authorization.k8s.io
