apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprotect-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vprotect-helm-operator
  template:
    metadata:
      labels:
        name: vprotect-helm-operator
    spec:
      serviceAccountName: vprotect-helm-operator
      containers:
        - name: vprotect-helm-operator
          # Replace this with the built image name
          image: quay.io/opentestlabs/vprotect-operator-helm:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vprotect-helm-operator"
            - name: RELATED_IMAGE_DB
              value: registry.redhat.io/rhel8/mariadb-103 
            - name: RELATED_IMAGE_INITCONTAINER
              value: quay.io/opentestlabs/initimage-ubi8
            - name: RELATED_IMAGE_SERVER
              value: image-registry.openshift-image-registry.svc:5000/demo-rhel/vprotect-node-server:0.1 
            - name: RELATED_IMAGE_NODE
              value: image-registry.openshift-image-registry.svc:5000/demo-rhel/vprotect-node-uid:0.0.1
