{{- if .Values.server.routes.secureRoute.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.server.routes.secureRoute.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-server
spec:
  to:
    kind: Service
    name: {{ .Values.server.service.svcName }}
    weight: 100
  port:
    targetPort: {{ .Values.server.service.securePort.name }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
