{{- if .Values.server.routes.insecureRoute.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.server.routes.insecureRoute.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vprotect-server
spec:
  to:
    kind: Service
    name: {{ .Values.server.service.svcName }}
    weight: 100
  port:
    targetPort: {{ .Values.server.service.insecurePort.name }}
  wildcardPolicy: None
{{- end }}
